### ISSUE TITLE
requirements failed

### ISSUE THREAD

**Issue by ignorance-k** [trusthlt/legal-argument-reasoning-task#2]
When I was configuring my environment, I encountered the following error. When I was configuring my environment, I encountered the following error. I don't know if it's the reason why I made a mistake, but I hope to get an answerI don't know if it's the reason why I made a mistake, but I hope to get an answer.

ERROR: Cannot install -r requirements.txt (line 13), -r requirements.txt (line 15), -r requirements.txt (line 24), -r requirements.txt (line 3), -r requirements.txt (line 51), -r requirements.txt (line 53), -r requirements.txt (line 54) and numpy==1.22.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.22.3
    altair 4.2.0 depends on numpy
    blis 0.4.1 depends on numpy>=1.15.0
    captum 0.5.0 depends on numpy
    datasets 1.18.1 depends on numpy>=1.17
    matplotlib 3.5.3 depends on numpy>=1.17
    mkl-fft 1.3.1 depends on numpy<1.23.0 and >=1.22.3
    mkl-random 1.2.2 depends on numpy<1.25.0 and >=1.24.3

**Comment by habernal** [comment]
Thanks, I could reproduce this issue. Seems like installing with conda should fix that ( see https://stackoverflow.com/questions/62688075/python-pip-install-mkl-fft-could-not-install ) but maybe we won't need this library at all. We're looking into that.

**Comment by LeonardBongard** [comment]
Hello @ignorance-k  and everyone following this issue,

I provided an update on the resolution of the dependency conflict problem. I have hopefully resolved the issue by adding a conda install script instead of the installation via pip.
Please follow the updated Instructions in the Readme file, and thanks for your interest in our project :)
